### PR TITLE
Add: Hydra configuration for fm-ledger-rules repository.

### PR DESCRIPTION
**Pull request by nc6**

### CODE REVIEW

**Comment by nc6** [comment]
@disassembler What's the motivation for using bors? We can do so, but it makes certain things annoying (e.g. no squash merges)

**Comment by dnadales** [comment]
I would also prefer not using `bors` at the moment. We're still a small team and the costs do not overweight the benefits IMHO...

BTW, we have a buildkite job that seems to be stale.

**Pull request merged**
