### PR TITLE
hydra-main:  use same commit as hydra-mantis

### PR DESCRIPTION
**Pull request by deepfire**
Mantis Hydra is submodule-capable.  Let's make our main Hydra as good.

### CODE REVIEW

**Comment by jmitchell** [comment]
@deepfire, have we confirmed the Hydra patches we maintain in this repo still make sense on this rev?

Would it be simpler to keep the same rev, and create an additional patch for submodule support?

**Comment by disassembler** [comment]
This is still pointing to our fork, with 2 additional commits on it. Here's a diff:
```

**Comment by deepfire** [comment]
@jmitchell, there are no patches involved on our fork of Hydra anymore, thankfully!

**Pull request merged**
