### PR TITLE
Use the .png version of the iohk logo in Hydra.

### PR DESCRIPTION
**Pull request by kreisys**
It looks better with a transparent background.

### CODE REVIEW

**Comment by cleverca22** [comment]
Screenshot_2019-04-04_19-17-37

looks a bit worse once its down-scaled to fit in the UI

**Comment by kreisys** [comment]
That's... strange. Doesn't look at all like that on my end 🤷‍♂️ 

Screen Shot 2019-04-04 at 6 19 24 PM

**Comment by cleverca22** [comment]
it may depend on resolution and DPI

**Comment by kreisys** [comment]
What’s bors and why ain’t it returning no status 🤨

**Comment by disassembler** [comment]
bors ping

**Pull request merged**
