### PR TITLE
[DEVOPS-1044] bors-ng: fix service restarting

### PR DESCRIPTION
**Pull request by rvl**

### CODE REVIEW

**Comment by rvl** [comment]
bors try

**Comment by jmitchell** [comment]
🎉

**Comment by rvl** [comment]
The number of PR approvals required to merge (if any) is configured in [bors.toml](https://github.com/input-output-hk/iohk-ops/blob/master/bors.toml). 

According to the [configured settings](https://bors-ng.aws.iohkdev.io/repositories/3/settings), anyone with push access to iohk-ops can run the `bors r+` command.

**Pull request merged**
