### PR TITLE
Add: Report status to fm-ledger-rules repo.

### PR DESCRIPTION
**Pull request by nc6**

### CODE REVIEW

**Comment by disassembler** [comment]
can you please change serokell -> Cardano? We're trying to disable the serokell project (and they're identical).

**Comment by dnadales** [comment]
> can you please change serokell -> Cardano? We're trying to disable the serokell project (and they're identical).

Done. Thanks for the review @disassembler

**Comment by dnadales** [comment]
@cleverca22 @disassembler `fm-ledger-rules` was renamed to `cardano-ledger-specs`, I guess this will require further changes. Could you point us to what we should change?

CC: @ruhatch

**Comment by disassembler** [comment]
The names in jobsets/default.nix and jobsets/spec.json

**Comment by dnadales** [comment]
> The names in jobsets/default.nix and jobsets/spec.json

Done. Thanks!

**Pull request merged**
