### PR TITLE
[DEVOPS-221] Replace cardano-sl Nix packaging with upstream

### PR DESCRIPTION
**Pull request by domenkozar**
## TODO

- [x]  [CSL-1509] Sadly `src = ./.;` in cardano-sl is really fragile, doing `nix-build -A cardano-sl-static` rebuilds the package atm. Two possible solutions:
   - more cardano-sl source to `src`
   - find another way to deterministically bring in a local path
- [ ] [DEVOPS-255] use different `dconfig` depending on target environment
- [x] [add `cardano-report-server-static` to cardano-sl](https://github.com/input-output-hk/cardano-sl/pull/1448)
- [x] wait for merge of https://github.com/input-output-hk/cardano-sl/pull/1320 and use the new master branch of cardano-sl

### CODE REVIEW

**Comment by cleverca22** [comment]
https://github.com/input-output-hk/cardano-sl/pull/1360

**Comment by deepfire** [comment]
Merged into `iohk-ops` `staging` branch.

**Comment by domenkozar** [comment]
DEVOPS-255 is taking too long, I will just prepare this and merge. We can add the constants later on.

**Comment by domenkozar** [comment]
Hydra test failures are unrelated.

**Pull request merged**
