### PR TITLE
[DEVOPS-203] also report to github the status on every cardano PR

### PR DESCRIPTION
**Pull request by cleverca22**

### CODE REVIEW

**Comment by domenkozar** [comment]
This should be merged only when stack2nix is removed from allowed failures. And that depends on a few things like newer Nix.

**Comment by cleverca22** [comment]
sure, shal i close this or just leave it open until then?

**Comment by domenkozar** [comment]
It's fine to have it open, hopefully soon :)

**Comment by domenkozar** [comment]
To be merged after DEVOPS-221 is done.

**Pull request merged**
