### PR TITLE
Buildkite: fix NIX_PATH and add deployment key for haskell.nix

### PR DESCRIPTION
**Pull request by rvl**
Fix problems found when doing input-output-hk/haskell.nix#93.

### CODE REVIEW

**Comment by rvl** [comment]
> Is there anyway one could exfil this key?

Yes, a buildkite build could `cat` the ssh key file and it would appear in the logs.

**Comment by angerman** [comment]
> > Is there anyway one could exfil this key?
> 
> Yes, a buildkite build could `cat` the ssh key file and it would appear in the logs.

Should we prevent buildkite to run on untrusted PRs then?

**Comment by rvl** [comment]
> Should we prevent buildkite to run on untrusted PRs then?

Yes. Already, Buildkite will not run PR builds from users who don't have repo write access.

**Pull request merged**
